ARDUINO_DIR  = /usr/share/arduino

ARDUINO_LIBS = Wire Servo Adafruit_Sensor Adafruit_BNO055 Wire/utility

BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyO1

include /usr/share/arduino/Arduino.mk

reset::
	./reset.sh &
